name: Build and deploy Next.js App with Prisma to Azure Web App - Jiveesha

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Prisma: Generate Client
      - name: Generate Prisma Client
        run: npx prisma generate

      # 5. Build Next.js app
      - name: Build Next.js App
        run: npm run build

      # 6. Create and populate the publish directory
      - name: Create publish directory
        run: |
          mkdir -p publish
          # Copy the standalone server files
          cp -r .next/standalone/* ./publish/
          # Copy the public directory
          cp -r public ./publish/
          # Copy the complete .next directory (including static files)
          cp -r .next ./publish/
          # Copy package.json
          cp package.json ./publish/

      # 7. Upload artifact for deployment job
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Download artifact from build
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./node-app

      # 2. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 3. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Jiveesha'
          slot-name: 'Production'
          package: ./node-app
