name: Deploy Next.js app to Azure Web App - Jiveesha

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Setup Node.js (use same major version as Azure runtime)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Install dependencies and build once (catches build errors early)
      - run: npm ci
      - run: npm run build

      # 4. Login to Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 5. Deploy entire repo (including .next build) to Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Jiveesha'
          slot-name: 'Production'
          package: .
