name: Build & Deploy Next.js (standalone) to Azure Web App - Jiveesha

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      WEBAPP_NAME: 'Jiveesha'

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Setup Node.js (same major version as App Service runtime)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Install deps & build (standalone output)
      - name: Install & build
        run: |
          npm ci
          npm run build            # outputs .next/standalone
          mkdir -p publish
          cp -r .next/standalone/* publish/
          # copy static assets (Next expects them relative to .next/static)
          mkdir -p publish/.next
          cp -r .next/static publish/.next/
          # copy public folder for static files served via fs
          cp -r public publish/

      # 4. Azure login (OIDC)
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 5. Deploy publish folder to Web App (ZIP deploy)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'Production'
          package: publish
